__all__ = ["capsnet_1d_mnist_1",
           "capsnet_1d_mnist_2",
           "capsnet_1d_mnist_3",
           "capsnet_1d_mnist_4",
           "capsnet_1d_affnist_1",
           "capsnet_1d_hippo",
           "capsnet_1d_hippo_1",
           "capsnet_1d_hippo_2",
           "capsnet_1d_hippo_3",
           "capsnet_1d_hippo_4",
           "capsnet_1d_hippo_5",]